### ISSUE TITLE
About model_list in the code

### ISSUE THREAD

**Issue by YuPeize** [wangguanan/AlignGAN#1]
There are seven models in the code: 
`		self.model_list = []
		self.model_list.append(self.G_rgb2ir)
		self.model_list.append(self.G_ir2rgb)
		self.model_list.append(self.D_rgb)
		self.model_list.append(self.D_ir)
		self.model_list.append(self.D_rgb_warmup)
		self.model_list.append(self.D_ir_warmup)
		self.model_list.append(self.encoder)
		self.model_list.append(self.embeder)`
But it seems unclear in the paper. Can you explain the relationship bwteen them and the models in the paper, especially D_rgb and D_rgb_warmup?

**Comment by wangguanan** [comment]
Thanks for your attention to our work.

Our training strategy is as below:
(1) warmup feature-alignment-module, i.e. train it like an IDE model
(2) warmup pixel-alignment-module, i.e. train it like a CycleGAN. The D_ir_warmup and D_rgb_warmup are used in this stage.
(3) train our AlignGAN module. D_ir and D_rgb are used here.
It's easy to understand why we need to init a new D_ir instead of using D_ir_warmup, because they have different architectures.
Maybe, It's a little difficult to understand why the D_rgb is newly defined? Why don't I straightly use D_rgb_warmup, because they have the same architecture. 
Here, we define it for new parameters.
Because we found if we use warmed parameters, the performance will drop. This may because that the two asymmetric discriminators （a warmed, a randomly initialized) make GAN training more difficult.
