### ISSUE TITLE
Question about statistic of sysu-mm

### ISSUE THREAD

**Issue by miracle24** [wangguanan/AlignGAN#9]
Hello. I download the dataset, sysu-mm, from the provided baiduyun link. And when I run your code, I got the statistic of this dataset as:
![image](https://user-images.githubusercontent.com/10026242/74915980-04791a00-5400-11ea-829f-8d8b70dd1714.png)

And I got the performance result as:
![image](https://user-images.githubusercontent.com/10026242/74916094-39856c80-5400-11ea-8f51-494237344d4e.png)
which is inferior to that reported in the paper.

I wonder whether the problem of dataset causes inferior performance.
By the way, I use 4 1080Ti GPUs with 30G memory. My environment setting is: pytorch==1.1.0, python=3.7.6, torchvision=0.2.0.

Thanks a lot.

**Comment by wangguanan** [comment]
Hi dear, thanks for your attention yo our work.

The results of our provided pre-trained model are a little different from the ones reported in our paper, which is caused by the randomness of the training stage.

In Question https://github.com/wangguanan/AlignGAN/issues/4, when training our AlignGAN, @heerduo got the results which are a little better than our pre-trained one.
You can also train our AlignGAN by yourself and may obtain better results.

**Comment by miracle24** [comment]
Sorry for the incomplete question. My bad.
   
 I noticed that the statistic of sysu-mm used in my experiment, i.e. 22258 RGB images and 11909 IR images for training,  does not match the experiment setting described in your paper, in which the training set contains 19659 RGB images and 12792 IR images. I wonder which training setting is exactly used to training the whole network in your work.  Maybe such inconsistency can account for the inferior performance I got.
 
If there is something wrong with sysu-mm, could you help me to fix it by, like, sharing me with your dataset used in your experiment?  I would appreciate that.

Best wishes!

**Comment by wangguanan** [comment]
I got the same RGB and IR number as your image capture when performing the official dataset.
So, I should not be the problem of your dataset.
I will check the problem recently. If you find the solution, please tell me, thank you a lot.
